pretrained_path: /mnt/home/csl426-aicr-ae5f63/.cache/huggingface/hub/models--openbmb--VoxCPM2/snapshots/bffb3df5a29440629464e5e839f4d214c8714c3d

# 全參數微調 (Full Fine-Tuning) 對照組 1：純 tai8 資料集
train_manifest: /mnt/home/csl426-aicr-ae5f63/dataset202607_1/tai8/manifests/voxcpm2_abs/train.jsonl
val_manifest: /mnt/home/csl426-aicr-ae5f63/dataset202607_1/tai8/manifests/voxcpm2_abs/val_seen.jsonl
sample_rate: 16000
out_sample_rate: 48000

batch_size: 4
grad_accum_steps: 8
num_workers: 8
max_batch_tokens: 8192

num_iters: 7000
max_steps: 7000
log_interval: 50
valid_interval: 500
save_interval: 1000

learning_rate: 0.00001
weight_decay: 0.01
warmup_steps: 500
max_grad_norm: 1.0

save_path: /app/checkpoints/full_ft_tai8
tensorboard: /app/checkpoints/full_ft_tai8/logs
lambdas:
  loss/diff: 1.0
  loss/stop: 1.0
